---
sudo: false
language: ruby
cache: bundler
script: 'bundle exec rake validate lint spec'
before_install:
  - gem update bundler
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.5
    env: PUPPET_GEM_VERSION="~> 5.5"
  - rvm: 2.5.3
    env: PUPPET_GEM_VERSION="~> 6"
notifications:
  email:
    - kotty@guns-n-girls.de
